# Generated by Django 4.1.1 on 2022-12-17 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_friendship_friendship_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower",
            field=models.ManyToManyField(
                through="accounts.Friendship", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
