# Generated by Django 4.1.1 on 2022-11-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_remove_tweetmodel_created_date_tweetmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetmodel",
            name="text",
            field=models.TextField(max_length=256),
        ),
    ]
