# Generated by Django 4.1.1 on 2022-12-01 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0005_alter_tweetmodel_text"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TweetModel",
            new_name="Tweet",
        ),
    ]
